Repository AyushMann29/EatNFun, pull requests merged in 2024-10, with the labels that each got.

#3 Completed issue 1
  index.html
Labels: hacktoberfest

#6 fixed popup text
  style.css
Labels: bug, hacktoberfest

#10 First
  index.html
  style.css
Labels: bug, hacktoberfest

#11 Added Footer section
  index.html
  style.css
Labels: enhancement, hacktoberfest

#14 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest

#16 Added Dark and light Mode
  .DS_Store
  dark.js
  images/.DS_Store
  index.html
  style.css
Labels: enhancement, hacktoberfest

#20 added the working scroll to top button
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 Enhancement of connect button
  index.html
  style.css
Labels: enhancement, good first issue, hacktoberfest

#25 added contact us page
  Contact_Us/contact-style.css
  Contact_Us/contact.html
  Contact_Us/script.js
  index.html
  style.css
Labels: hacktoberfest

#26 fixed the dark mode button #22
  index.html
  style.css
Labels: hacktoberfest

#33 fixed dropdown in navigation bar
  index.html
Labels: hacktoberfest

#32 Beautified Readme
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest

#36 Add favicon icon
  images/favicon.png
  index.html
Labels: hacktoberfest

#40 Add Event Feature to Calendar
  eventcalender.html
Labels: enhancement, hacktoberfest

#41 added flip card functionality
  index.html
  menu.js
  style.css
Labels: hacktoberfest

#43 Now popup text is visible clearly. placed in center
  .vscode/launch.json
  index.html
  style.css
Labels: hacktoberfest

#45 Solved Issue #44
  dark.js
Labels: hacktoberfest

#51 added logo closes #47
  images/logo.png
  index.html
  style.css
Labels: hacktoberfest

#60 Linked contact with contact page
  index.html
Labels: good first issue, hacktoberfest

#63 products changed
  index.html
Labels: enhancement, good first issue, hacktoberfest

#64 Connecting calenderevents with index
  index.html
  script.js
Labels: enhancement, hacktoberfest

#65 changed the twitter icon to the new x icon (issue #61)
  index.html
  style.css
  twitter-x.png
Labels: hacktoberfest

#68 Beautifying code
  index.html
Labels: enhancement, hacktoberfest

#69 about us page is added
  about.css
  about.html
  index.html
Labels: hacktoberfest

#70 Update README.md
  README.md
Labels: hacktoberfest

#73 Updated social links
  .vscode/settings.json
  index.html
Labels: enhancement, hacktoberfest

#74 Update about.css
  about.css
Labels: hacktoberfest

#83 Optimized Footer
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#86 Enhanced Styling and Layout for 'About Us' Page
  about.css
  about.html
  images/pexels-ekrulila-2307221.jpg
Labels: hacktoberfest

#87 Overlapping of text fixed
  style.css
Labels: bug, hacktoberfest

#88 Update service
  index.html
Labels: hacktoberfest
